Homework1
made-ml-in-prod-2022/POTATOCHKA pull request #1
Opened 2022-05-09 12:41 UTC by POTATOCHKA

Архитектурные решения:
В папке ./build_model лежат файлы с основными пайплайнами по обучению и предсказанию
В ./configs лежат два примера конфигов, в которых определены основные переменные для запуска скриптов обучения
В ./data/raw находится данные, которые использовались для обучения и предсказания
В ./data_explore лежит eda данного проекта
В ./models/{model_name} лежат метрики обученных можелей, а такж сохраненные веса
Для конфигурирования использовалась hydra
При запуске скриптов обучения создается папка outputs где сохраняются логи запусков
Для сущностей из конфигов были написаны датаклассы содержатся в файле ./utils/read_config.py
Кастомный трансформер данных содержится в ./utils/transform_class.py

2022-05-11 18:54 UTC, POTATOCHKA commented
Количество баллов после самооценки - 26 подробности в readme.md

2022-05-27 10:09 UTC, SVizor42 commented on ml_project/data_explore/eda.py
> +import tabulate
Импорт не используется

2022-05-27 10:22 UTC, SVizor42 commented on ml_project/utils/split.py
> +def split_and_save_data(full_df: pd.DataFrame, target: pd.DataFrame, dataclass_config: Config) -> Tuple[pd.DataFrame]:
Тут точно все возвращаемые типы DataFrames?

2022-05-27 10:23 UTC, SVizor42 commented on ml_project/utils/split.py
> +def split_and_save_data(full_df: pd.DataFrame, target: pd.DataFrame, dataclass_config: Config) -> Tuple[pd.DataFrame]:
+ строка слишком уж длинная получается

2022-05-27 10:25 UTC, SVizor42 commented on ml_project/utils/transform_class.py
> +
Лишний пробел

2022-05-27 10:39 UTC, SVizor42 commented on ml_project/utils/train_model.py
> +    path_to_model = hydra.utils.to_absolute_path(
А почему просто не вынести путь до модели в конфиг?

2022-05-27 10:47 UTC, SVizor42 commented on ml_project/build_model/predict.py
> +    df = pd.read_csv(hydra.utils.to_absolute_path(path=dataclass_config.test_data_path))
Лучше избегать в продакшен коде малоинформативных идентификаторов

2022-05-27 10:50 UTC, SVizor42 commented on ml_project/build_model/predict.py
> +    return None
`None `можно уж не возвращать :)

2022-05-27 10:51 UTC, SVizor42 commented on ml_project/build_model/predict.py
> +    path_to_model = hydra.utils.to_absolute_path(
Опять вопрос относительно пути к модели

2022-05-27 10:51 UTC, SVizor42 commented on ml_project/build_model/predict.py
> +    path_to_model = hydra.utils.to_absolute_path(
С трансформером схожая ситуация

2022-05-27 10:54 UTC, SVizor42 commented on ml_project/build_model/predict.py
> +    transform = pickle.load(open(path_to_transform, 'rb'))
Вроде требуется импортировать класс самого трансформера

2022-05-27 12:22 UTC, SVizor42 requested changes
Небольшие комментарии:
1. pycache нужно добавить в gitignore
2. Кастомный трансформер не протестирован
3. Добавь плиз docstrings (по усмотрению)
4. Самооценку лучше приводить в самом PR вместо README

2022-06-10 16:07 UTC, POTATOCHKA commented
поправил замечания. По поводу pycache не понял, не вижу его вообще в файлах. Тесты на трансформер добавил, процесс запуска описан в md файле. Докстринг не добавлял, мне говорили, что осмысленные названия переменных и тайпинги уже почти все объясняют, если из моего кода непонятно, могу в дальнейшем добавлять. Самооценку в дальнешем перемещу в PR.

2022-06-11 21:07 UTC, SVizor42 approved these changes
`__pycache__` лежит как минимум в `utils` и `build_model`. Тоже самое касается `.idea` от среды. Добавь их просто в `.gitignore`.
По остальным замечаниям ок. Потом можешь сливать ветку.

**Сумма: 26 баллов**

2022-06-15 16:33 UTC, merged